var width = 5;
var height = 7;
var area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
var bill = 34;
var payment = 50;
var change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
var quizzes = 90;
var midterm = 89;
var final = 80;
var grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade;', typeof grade);
var firstName = 'Louisa';
var lastName = 'Whitaker';
var fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', fullName);
var pH = 18;
var isAcidic = pH < 7;
console.log('value of Acidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
var headCount = 562;
var isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta;', typeof isSparta);
var motto = fullName += ' is the GOAT!';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
